env: env
database:
  host: 127.0.0.1
  port: 3306
  user: root
  password: Hexiang321#@!
  name: test



authRedis:
  password: Hexian%!g5tg
  db: 11
  host: 127.0.0.1 #172.18.214.173:6379
  port: 6379
